//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by sTask.rc
//
#define IDC_BTN_HELP                    3
#define IDD_ABOUTBOX                    100
#define IDD_PROP_ADD1                   107
#define IDR_MAINFRAME                   128
#define IDD_PROP_ADD2                   129
#define IDD_PROP_ADD3                   130
#define IDD_PROP_CNF1                   131
#define IDD_PROP_CNF2                   132
#define IDD_PROP_CNF3                   133
#define IDD_DEBUG                       134
#define IDD_DLG_PASSWD                  135
#define IDD_PROP_ADD4                   137
#define IDD_PROP_ADD0                   138
#define IDD_DLG_NORMAL                  139
#define IDR_SCRIPT                      144
#define IDD_DLG_INST                    145
#define IDI_ICO_INST                    148
#define IDR_STASKTYPE                   151
#define IDB_TRAIN                       152
#define IDD_PROP_ADD5                   155
#define IDR_JSCRIPT                     160
#define IDR_VBSCRIPT                    162
#define IDR_UNKNOWN                     164
#define IDR_XDOCICON                    185
#define IDC_EDIT_FPASS                  1000
#define IDC_BTN_BROWSE                  1001
#define IDC_EDIT_PARAM                  1002
#define IDC_EDIT_COMMENT                1003
#define IDC_CHECK_ON                    1004
#define IDC_COMBO_APART                 1005
#define IDC_EDIT_NAME                   1005
#define IDC_EDIT_EXECDIR                1006
#define IDC_TEXT_APART                  1007
#define IDC_BTN_EXECDIR                 1007
#define IDC_CHECK_WAIT                  1008
#define IDC_BTN_POWERTEST               1008
#define IDC_CHECK_MON                   1009
#define IDC_CHECK_STOP                  1010
#define IDC_CHECK_STDLG                 1011
#define IDC_CHECK_THU                   1012
#define IDC_CHECK_PREVTASK              1012
#define IDC_CHECK_FRI                   1013
#define IDC_CHECK_SAT                   1014
#define IDC_LFNAME                      1014
#define IDC_INOUT_TIME0                 1015
#define IDC_PRGRESS                     1015
#define IDC_INPUT_TIME1                 1016
#define IDC_MES                         1016
#define IDC_EDIT_INTERVAL               1017
#define IDC_CHECK_TIME                  1018
#define IDC_EDIT_WAIT                   1019
#define IDC_CHECK_SUN                   1020
#define IDC_EDIT_STOP                   1020
#define IDC_CHECK_TUE                   1021
#define IDC_EDIT_EXEC                   1021
#define IDC_CHECK_WED                   1022
#define IDC_EDIT_CHECK                  1022
#define IDC_G_PASSWD                    1024
#define IDC_G_TIME1                     1025
#define IDC_G_TIME2                     1026
#define IDC_G_SECURE                    1027
#define IDC_DLG                         1028
#define IDC_BTN_IN_ST                   1028
#define IDC_DLG0                        1029
#define IDC_BTN_IN_CONF                 1029
#define IDC_UNIN_ST                     1030
#define IDC_EDIT_TIME1                  1030
#define IDC_G_DELAY                     1031
#define IDC_BTN_UNIN_CONF               1031
#define IDC_EDIT_TIME2                  1031
#define IDC_G_FAILDLG                   1032
#define IDC_UNIN_REG                    1032
#define IDC_BTN_WR_REGST                1033
#define IDC_BTN_RM_REGST                1034
#define IDC_NOW_DATE                    1035
#define IDC_NOW_TIME                    1036
#define IDC_EDIT                        1039
#define IDC_PROP1_NAME                  1042
#define IDC_R_SEL1                      1043
#define IDC_R_SEL2                      1044
#define IDC_R_SEL3                      1045
#define IDC_RECOMMEND                   1047
#define IDC_WINFILE                     1048
#define IDC_R_TYPE                      1048
#define IDC_R_TYPE2                     1049
#define IDC_INFOUNINST                  1050
#define IDC_BTN_PASS                    1051
#define IDC_MESSAGE                     1052
#define IDC_BTN_MKUNIN                  1052
#define IDC_R_AUTOEXEC                  1053
#define IDC_R_AUTOEXEC2                 1054
#define IDC_R_AUTOEXEC3                 1055
#define IDC_R_AUTOEXEC4                 1056
#define IDC_CHECK_UNINST_CPL            1057
#define IDC_CHECK_UNINST_START          1058
#define IDC_CMB_SYNCEXEC                1058
#define IDC_PROP5_NAME                  1060
#define IDC_CMB_WNDSTYLE                1061
#define IDC_CMB_CURDIR                  1063
#define IDC_CMB_POWERSTAT               1063
#define IDC_EDIT_CURDIR                 1064
#define IDC_BTN_CURDIR                  1065
#define IDC_CMB_EXECDIR                 1066
#define ID_TASK_NEW                     32771
#define ID_WRITEREG                     32772
#define ID_VIEW_ICON                    32773
#define ID_VIEW_REPORT                  32774
#define ID_TASK_UP                      32775
#define ID_DEBUG                        32776
#define ID_TASK_DOWN                    32777
#define ID_TASK_OFF                     32778
#define ID_CONFIG                       32779
#define ID_TASK_EXEC                    32780
#define ID_TASK_CONFIG                  32781
#define ID_TASK_CUT                     32782
#define STR_PAS_INPOLD                  61204
#define STR_APPNAME                     61205
#define STR_FIL_SEL                     61206
#define STR_ERRPAS                      61207
#define STR_DLG_PARERR                  61208
#define STR_PAS_IMP                     61209
#define STR_FIL_CNFNAME                 61210
#define STR_FIL_AUTNAME                 61211
#define STR_NAME_SCANDISK               61212
#define STR_NAME_DEFRAG                 61213
#define STR_NAME_SYSFILCHK              61214
#define STR_NAME_DISKCLEAN              61215
#define STR_NAME_REGCHK                 61216
#define STR_PER_LOGON                   61217
#define STR_PER_DAY                     61218
#define STR_PER_WEEK                    61219
#define STR_PER_MONTH                   61220
#define STR_PER_RANDOM                  61221
#define STR_PAS_IMPNEW                  61223
#define STR_PAS_IMPCONFIRM              61224
#define STR_PAS_CHANGEOK                61225
#define STR_PAS_CHANGENG                61226
#define STR_REGKEY_STARTUP              61227
#define AFX_STR_LINK_PROG               61229
#define AFX_STR_LINK_STARTUP            61230
#define STR_PAS_ERR_OFF                 61231
#define STR_EXEC_DEBUG                  61232
#define STR_EXEC_DEBUG_TITLE            61233
#define STR_EXEC_NORM                   61234
#define STR_ERR_DLGCREATE               61235
#define STR_EXEC_DLGPRGRESS             61236
#define STR_EXEC_STOP                   61237
#define STR_NEXEC_NREACH                61238
#define STR_NEXEC_EXCLUDETIME           61239
#define STR_NEXEC_EXCLUDEDAY            61240
#define STR_NEXEC_COUNTER               61241
#define STR_NEXEC_EXECERR               61242
#define STR_SUN                         61243
#define STR_MON                         61244
#define STR_TUE                         61245
#define STR_WED                         61246
#define STR_THU                         61247
#define STR_FRI                         61248
#define STR_SAT                         61249
#define AFX_STR_LINK_UNINST             61250
#define AFX_STR_UNINST_CPLNAME          61251
#define AFX_STR_USERDAT_1               61252
#define AFX_STR_USERDAT_2               61253
#define STR_MES_UNIN_CUR                61254
#define STR_MES_UNIN_ADM                61255
#define STR_MES_UNIN_NOT                61256
#define STR_MES_NEW_PASSWORD            61257
#define STR_NAME_DEFRAG2000             61258
#define STR_NAME_SVC                    61259
#define STR_NAME_EVENTVWR               61260
#define STR_MES_DEBUG_NOSAVE            61261
#define STR_VIEW_TASK                   61262
#define STR_VIEW_SCHEDULE               61263
#define STR_VIEW_PREVEXEC               61264
#define STR_VIEW_NEXTEXEC               61265
#define STR_VIEW_STATUS                 61266
#define STR_VIEW_ADD_NEW_ITEM           61267
#define STR_EXCEPTION                   61268
#define STR_VIEW_WAITPREV               61269
#define STR_VIEW_LOOKPREV               61270
#define STR_VIEW_LIST_DATETIME          61271
#define STR_VIEW_AT_LOGON               61272
#define STR_VIEW_STOP_STATE             61273
#define STR_ERR_NOADD_NOTASKNAME        61274
#define STR_ERR_NOEDIT_NOTASKNAME       61275
#define STR_TASK_CONFIG_SHORT           61276
#define STR_CONFIG_SHORT                61277
#define STR_MES_EXIT_DEBUG              61278
#define STR_MES_REGSAVED                61279
#define STR_TASK_NEW_SHORT              61280
#define AFX_STR_ERR_HELP                61281

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
